### ISSUE TITLE
Add Hinge Angles Support Request

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [AIS-Bonn/rot_conv_lib#1]
Hi, would it be possible to add implementation of "Hinge Angles for 3D Discrete Rotations" to this library, please?

(http://www.dgcv.nii.ac.jp/Publications/Papers/2009/IWCIA2009a.pdf)

**Comment by pallgeuer** [comment]
This library is mainly intended for continuous real 3D rotations, and hinge angles are for discrete pixel/voxel-style rotations. Is it even clear how to convert an arbitrary 3D rotation into its 'closest' 3D hinge angles rotation? Are there standard formulas for that anywhere?

You could try constructing an extra header (e.g. rot_conv_discrete.h) in the same style as the library just for yourself for now that implements a HingeAngles (POD) type and see how far you get?

**Comment by neurodiverseEsoteric** [comment]
Oh, sorry, I didn't read the article...I thought it was a similar concept as an alternative 3d rotation system...
