### ISSUE TITLE
OpenGL/X.org/X11 math help

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [AIS-Bonn/rot_conv_lib#2]
If one wanted to make a transform node for any linux 3d DCC app that relied on fused and/or tilt angles instead of tait-bryan/euler angles, how would one program all the stuff that converts cursor movements (driven by any device, be it a mouse, tablet, keyboard, or accessability hardware such as pedals or IR pointers) into values as shown in a rotation parameter/channel/attribute editor? Would fused/tilt angles have a more seamless two-way relationship between the values computed by a 3d scene interaction and the values manually set by the animator via a spreadsheet/keyframe-style editor?

**Comment by pallgeuer** [comment]
So I'm not a pro on animator software and how exactly all that is/should be implemented, but I strongly feel that if anything the tilt phase space would be the right thing for the job. I for my own applications create cubic spline orientation trajectories in that space, and it would allow a nice split of 3D rotations into a single fused yaw slider and a pitch/roll planar input. Both these seem made for cursor/keyboard input, and I argue the output of what happens in terms of rotations is quite intuitive/logical. Clearly, just as Euler angles have two singularities (positive and negative gimbal lock), it's not possible to get away without for 3 parameters, so the fused yaw would become problematic for completely 180 degree upside down poses.

**Comment by neurodiverseEsoteric** [comment]
I also don't know what the standard implementation is, since they are nearly all proprietary,  asides from Blender and https://github.com/CedricGuillemet/ImGuizmo ...The issue pervades every DCC app at the moment, that rotation changes made by interacting with a 3d object (computed using projections with added event history) almost never correspond with rotation changes made parametrically (directly setting Rx/Ry/Rz/ROrd values—in degrees—in 2D text-boxs which are then directly applied to the local transformation matrix of the cooresponding object)...

**Comment by pallgeuer** [comment]
Although this may be a problem with current DCC apps, and I'm not sure what the best solution is, this does not seem to be an 'issue' with rot_conv_lib, so I'm going to close this issue.

**Comment by neurodiverseEsoteric** [comment]
I submitted it to be more of a plea and/or a  'feature request'
